---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bundle-data-cryptor
  namespace: {{ .Release.Namespace }}
  labels:
    type: nfs
    name: pv-bundle-data-cryptor
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - lookupcache=pos
  nfs:
    path: {{ .Values.pv.path }}
    server: {{ .Values.pv.server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bundle-data-cryptor
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: pvc-bundle-data-cryptor
      type: nfs
